package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/3)
=> update package name

contracts/reward/OnePoolReward.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/4)
=> Adjust rewardable range

hardhat.config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/5)
=> add config for 0g testnet

contracts/dataFlow/FixedPriceFlow.sol, contracts/dataFlow/Flow.sol, contracts/interfaces/IReward.sol, contracts/market/FixedPrice.sol, contracts/reward/ChunkRewardBase.sol, contracts/reward/OnePoolReward.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/6)
=> Fix bugs in the first market implementation

contracts/reward/OnePoolReward.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/7)
=> Implement reward donation

contracts/miner/Mine.sol, contracts/test/PoraMineTest.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/8)
=> Adjust quality

README.md, scripts/deploy.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/9)
=> Update deploy script for mine contract

contracts/dataFlow/Flow.sol
- Change makeContext() from recursion to loop
- Add new makeContextFixedTimes() to make fixed epochs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/10)
=> feat: refactor makeContext()

contracts/interfaces/IFlow.sol, contracts/miner/Mine.sol, contracts/miner/MineLib.sol, contracts/miner/RecallRange.sol, contracts/utils/Blake2b.sol, test/mine.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/12)
=> Implement mining on sharded storage. 

hardhat.config.ts, src/config.ts, src/networks/zerog_contract_config.ts, src/networks/zerog_testnet_contract_config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/14)
=> chore: network configuration update

contracts/cashier/Cashier.sol, contracts/dataFlow/Flow.sol, contracts/dataFlow/FlowTreeLib.sol, contracts/market/FixedPrice.sol, contracts/miner/Mine.sol, contracts/reward/ChunkDecayReward.sol, contracts/reward/ChunkLinearReward.sol, contracts/reward/ChunkRewardBase.sol, contracts/reward/OnePoolReward.sol, contracts/test/MerkleTreeTest.sol, contracts/utils/ZgInitializable.sol, package.json, src/deploy/deploy_blake2b_test.ts, src/deploy/deploy_chunk_linear_reward.ts, src/deploy/deploy_fixed_price_market.ts, src/deploy/deploy_market_enabled_initialization.ts, src/deploy/deploy_no_market_initialization.ts, src/utils/utils.ts, test/blake2b.spec.ts, test/merkle.spec.ts, test/mine.spec.ts, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/16)
=> Switch to chunk linear reward

src/dev/view.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/18)
=> Fix dev script

contracts/market/FixedPrice.sol, contracts/miner/Mine.sol, contracts/miner/RecallRange.sol, contracts/reward/ChunkLinearReward.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/19)
=> Fix shard difficulty setting

contracts/reward/ChunkRewardBase.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/21)
=> Fix issue found in audition

contracts/reward/ChunkRewardBase.sol, contracts/utils/PullPayment.sol, src/dev/view.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/22)
=> Fix PullPayment in upgradable contract

contracts/dataFlow/FlowTreeLib.sol, contracts/miner/MineLib.sol, contracts/utils/Exponent.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/24)
=> Cleanup solidity logs

src/deploy/deploy_market_enabled_initialization.ts, src/dev/view.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/25)
=> fix: deployment scripts

contracts/dataFlow/Flow.sol, contracts/dataFlow/FlowTreeLib.sol, contracts/utils/ZgsSpec.sol, test/flow.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/27)
=> refactor: flow padding

.gitignore, contracts/dataFlow/FixedPriceFlow.sol, contracts/dataFlow/Flow.sol, contracts/interfaces/IFlow.sol, hardhat.config.ts, package.json, src/tasks/access.ts, src/tasks/upgrade.ts, src/utils/utils.ts, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/28)
=> feat: root history; chore: upgrade scripts

contracts/dataFlow/Flow.sol, hardhat.config.ts, src/deploy/constructor_args.ts, src/deploy/deploy_chunk_linear_reward.ts, src/deploy/deploy_fixed_price_flow.ts, src/deploy/deploy_flow.ts, src/deploy/deploy_market_enabled_initialization.ts, src/deploy/deploy_one_pool_reward.ts, src/deploy/deploy_pora_mine.ts, src/deploy/deploy_pora_mine_test.ts, src/tasks/upgrade.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/30)
=> fix: rootByTxSeq; chore: add getConstructorArgs()

contracts/dataFlow/FlowTreeLib.sol, src/deploy/deploy_fixed_price_market.ts, src/deploy/deploy_market_enabled_initialization.ts, src/tasks/upgrade.ts, src/utils/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/33)
=> fix: pad boundary case; chore: upgrade tasks

contracts/dataFlow/Flow.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/32)
=> Add flow root query interface

src/deploy/deploy_market_enabled_initialization.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/34)
=> fix default price

src/tasks/upgrade.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/35)
=> chore: scripts

src/deploy/deploy_chunk_linear_reward.ts, src/deploy/deploy_fixed_price_flow.ts, src/deploy/deploy_flow.ts, src/deploy/deploy_one_pool_reward.ts, src/deploy/deploy_pora_mine.ts, src/deploy/deploy_pora_mine_test.ts, src/tasks/upgrade.ts, src/utils/constructor_args.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/36)
=> fix: deploy

contracts/dataFlow/Flow.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/38)
=> remove assert in make context

src/dev/view.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/40)
=> update contract view scripts for dev

contracts/miner/Mine.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/41)
=> feat: set minimum difficulty for PoRA mine

hardhat.config.ts, src/tasks/mine.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/39)
=> add function to update the mine parameters

contracts/miner/Mine.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/42)
=> feat: add version interface for PoRA mine

.eslintrc.js, .github/workflows/ci.yml, contracts/dataFlow/Flow.sol, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/44)
=> Fix lint errors in CI

contracts/miner/MineLib.sol, contracts/utils/ZgsSpec.sol, test/mine.spec.ts, test/utils/params.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/46)
=> feat: Implement EVM-friendly scratch pad

contracts/miner/Mine.sol, contracts/miner/WorkerContext.sol, contracts/test/PoraMineTest.sol, test/mine.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/47)
=> feat: Introduce sub-task for PoRA mine.

hardhat.config.ts, src/tasks/mine.ts, src/tasks/reward.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/51)
=> add mine and reward tasks

contracts/reward/ChunkLinearReward.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/52)
=> add current block timestamp in firstRewardableChunk return

contracts/dataFlow/Flow.sol, contracts/miner/Mine.sol, contracts/utils/BlockHash.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/54)
=> Adapt EIP-2935 and fix an issue on empty context digest

contracts/miner/Mine.sol
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-contracts/57)
=> fix difficulty change in new epoch
